# -*- coding: utf-8 -*-
"""A108060082week8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lTWCw4bFSBm_iVzJx5Ctk0EeS8vmBLr3
"""

movie＿title=("魔球")

movie＿time=("133分鐘")

print(movie_time)

movie＿time=("2小時13分鐘")

print(movie_time)

