# -*- coding: utf-8 -*-
"""week7homework

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RNCNvbdxXA3Fc1la2aoK5TAoJ2Wr5lxw
"""

movie_title="梨泰院"

release_year='2020'

movie_episode＝16

movie_rating=8.3

director1="金成允"

director2="姜敏九"

star_1="朴敘俊"

star_2="金多美"

star_3="權娜拉"

star_4="劉在明"

like=1

print(movie_title)

print(release_year)

print(movie_rating)