# -*- coding: utf-8 -*-
"""week6作業.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wmzyQzPvuIGnwMWjEFKN-u9exGV2kwXx
"""

name=input("Enter your name.")

print("我的名字是","張書瑜")

name="張書瑜"
print("我的名字是：",name)

name=input("請輸入你的名字")
print("名字為",name)

age=input("Enter your age: ")

print("我的年紀是",18,"歲")

year=18
print("我的年紀是",year,"歲")

year=input("請輸入你的年紀")
print("年紀是",year)

weight=input("Enter your weight:")

print("我的體重是",55,"公斤")

weight=55
print("我的體重是",55,"公斤")

weight=input("請輸入你的體重")
print("體重是",55)

