# -*- coding: utf-8 -*-
"""week12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AkoyzVmubEI54kIoOlbrNnPLSxg7aa2_
"""

noodle = input("有麵嗎?(YES/NO)")

sauce = input("有醬料嗎?(YES/NO)")

if noodle == "YES" :
        if sauce == "YES" :
                print("讓我們來做義大利麵吧!")

#更簡潔的寫法

if noodle == "YES" and sauce == "YES":
    print("讓我們來做義大利麵吧!")

