# -*- coding: utf-8 -*-
"""week13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lFF94b9awCJPmhA8_HJwiDN23sLr9pUa
"""

score = int(input("請輸入成績"))
if score >= 80:
        print("非常好")
if 80 > score >= 60:
        print("不錯喔")
if score < 60:
        print("要加油")

score = int(input("請輸入成績"))
if score >= 80:
          print("非常好")
else:
          if score >=60 :
                  print("不錯喔")
          else:
                  print("要加油")

score = int(input("請輸入成績"))
if score >=80:
          print("非常好")
elif score >= 60:
          print("不錯喔")
else :
          print("要加油")

